feat(parser): add deprecation information for field arguments
brettchalupa/graphql-docs pull request #135
Opened 2023-03-09 19:09 UTC by jeromedalbert

Just like fields have deprecation information, add deprecation information for field arguments as well.

This is useful information that has been missing so far from the parser. It can be used by custom templates that display deprecated arguments differently, such as showing a warning or hiding the deprecated argument altogether.

The implementation follows the same logic as `field` a few lines above.

2023-03-09 20:49 UTC, brettchalupa requested changes
Thanks for this, I really appreciate it! Code looks good to me, but would you be up for adding a unit test for it? Let me know if I can be of any help there if you need it.

2023-03-09 20:49 UTC, brettchalupa commented
Also, I see the Ruby 2.6.10 tests are failing, but that looks to be unrelated to your changes. I'll work on fixing that in `main`.

2023-03-11 00:00 UTC, merged

2023-03-11 00:00 UTC, brettchalupa commented
@jeromedalbert thanks again for the contribution! I'll cut a 4.1 release early next week with the change.

2023-03-11 01:13 UTC, jeromedalbert commented
Cool, thanks!